// Imports: Dependencies
import {all, fork} from 'redux-saga/effects';
// Imports: Redux Sagas
import {
  userSignup,
  phoneVerify,
  verifyOTP,
  userLogin,
  userDetails,
  resetPasswordByMobile,
  resetPasswordConfirmOTP,
  resetPassword,
  updateUserData,
  userLogout,
  saveMissingEntity,
  userPasswordChange,
  createUserBioMetrics,
  updateUserBioMetrics,
  getUserBioMetrics,
  getTodaySessions,
  updateBiometricsSettings,
  getBiometricsSettings,
} from './user/saga';
import {
  getAllQongfus,
  getAllLifestyles,
  getPlaces,
  searchPlaces,
  getPlace,
  savePlaceRating,
  fecthInitialData,
  searchSuggestions,
  fetchGlobalConfig,
  fetchFirebaseToken,
  getPlaceGalleries,
  getPlaceRatings,
} from './app/saga';
import {fetchAllPlaces} from './map/saga';
// import {getPlaceRating} from './ratings/saga';
import {
  savePlaceMedias,
  getPlaceMedias,
  deletePlaceMedias,
  reportAPost,
  updatePlaceMedia,
  getMediaPost,
  updateMediaPosition,
} from './places/saga';
import {
  fetchAccountStatus,
  deactivateBusinessAccount,
  createPlace,
  updatePlace,
  fetchUserPlaces,
  getUserPlace,
  createClaim,
  fetchBusinesses,
  updateClaim,
  reportAReview,
  fetchReportedReviews,
  deleteReportedReview,
  searchUnClaimed,
  createCalenderSchedule,
  updateCalenderSchedule,
  deleteCalenderSchedule,
  getBusinessPlaceGalleries,
  getBusinessPlaceRatings,
} from './business/saga';

import {
  fetchContactStatus,
  sendInvitation,
  fetchFriends,
  createFriend,
  updateFriend,
  getFriend,
  deleteFriend,
} from './friends/saga';

// Redux Saga: Root Saga
export function* rootSaga() {
  yield all([
    fork(userSignup),
    fork(phoneVerify),
    fork(verifyOTP),
    fork(userLogin),
    fork(userDetails),
    fork(resetPasswordByMobile),
    fork(resetPasswordConfirmOTP),
    fork(resetPassword),
    fork(updateUserData),
    fork(getAllQongfus),
    fork(getAllLifestyles),
    fork(getPlaces),
    fork(searchPlaces),
    fork(getPlace),
    fork(savePlaceRating),
    fork(userLogout),
    fork(saveMissingEntity),
    fork(fecthInitialData),
    fork(userPasswordChange),
    fork(fetchAllPlaces),
    fork(getPlaceRatings),
    fork(searchSuggestions),
    fork(savePlaceMedias),
    fork(getPlaceMedias),
    fork(deletePlaceMedias),
    fork(fetchAccountStatus),
    fork(deactivateBusinessAccount),
    fork(fetchGlobalConfig),
    fork(createPlace),
    fork(updatePlace),
    fork(fetchUserPlaces),
    fork(getUserPlace),
    fork(createClaim),
    fork(fetchBusinesses),
    fork(updateClaim),
    fork(reportAReview),
    fork(fetchReportedReviews),
    fork(deleteReportedReview),
    fork(reportAPost),
    fork(updatePlaceMedia),
    fork(getMediaPost),
    fork(searchUnClaimed),
    fork(updateMediaPosition),
    fork(createCalenderSchedule),
    fork(updateCalenderSchedule),
    fork(deleteCalenderSchedule),
    fork(fetchFirebaseToken),
    fork(getPlaceGalleries),
    fork(getBusinessPlaceRatings),
    fork(getBusinessPlaceGalleries),
    fork(fetchContactStatus),
    fork(sendInvitation),
    fork(fetchFriends),
    fork(createFriend),
    fork(updateFriend),
    fork(getFriend),
    fork(deleteFriend),
    fork(createUserBioMetrics),
    fork(updateUserBioMetrics),
    fork(getUserBioMetrics),
    fork(getTodaySessions),
    fork(updateBiometricsSettings),
    fork(getBiometricsSettings),
  ]);
}
