import {StyleSheet} from 'react-native';
import theme from './theme.style';

const styles = StyleSheet.create({
  imageContainer: {
    flexDirection: 'column',
    height: 220,
    position: 'relative',
    // marginTop: 13,
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
  },
  headerContainer: {
    elevation: 1,
    marginBottom: 10,
    flexDirection: 'column',
    position: 'relative',
  },
  headerLogoTab: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    position: 'relative',
  },
  headerAvatar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    alignItems: 'center',
    // backgroundColor: 'red',
    zIndex: 1,
  },
  headerLogoContain: {
    position: 'absolute',
    bottom: -50,
    left: 20,
  },
  headerLogo: {
    backgroundColor: '#fff',
  },
  cameraIcon: {
    backgroundColor: '#000',
    opacity: 0.4,
    borderRadius: 5,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 6,
    paddingBottom: 6,
  },
  cameraIconContainer: {
    position: 'absolute',
    top: 120,
    left: 30,
    width: '100%',
    alignItems: 'center',
    zIndex: 999,
    // backgroundColor: 'green',
  },
  cameraCoverIcon: {
    position: 'absolute',
    right: 10,
    top: 10,
    alignItems: 'center',
    zIndex: 99,
  },
  emptySection: {
    fontSize: 20,
    color: '#e5e3e3',
    margin: 40,
    textAlign: 'center',
  },
  sections: {
    padding: 16,
  },
  placeProfileTitle: {
    fontSize: 24,
    lineHeight: 35,
    color: '#858585',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textTransform: 'capitalize',
  },
  mediaImage: {
    height: 180,
    width: '100%',
  },
  coverImage: {
    height: 220,
  },
  ratingContainer: {
    position: 'absolute',
    bottom: 2,
    right: 0,
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  starRatingContain: {
    backgroundColor: '#4f4d4b82',
    height: 23,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    paddingLeft: 10,
    paddingRight: 3,
  },
  ratingStyle: {
    color: '#4f4f4f',
    fontSize: 16,
    paddingLeft: 3,
    paddingRight: 10,
    height: 23,
    backgroundColor: '#4f4d4b82',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  placeHrsContainer: {
    backgroundColor: '#E5E3E3',
    textTransform: 'uppercase',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    paddingLeft: 10,
    paddingRight: 10,
    marginLeft: 10,
    marginRight: 5,
  },
  placeCardDesc: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  placeName: {
    fontSize: 24,
    color: '#4F4F4F',
    lineHeight: 35,
    marginTop: 10,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    marginTop: 40,
  },
  shieldIcon: {
    marginTop: 35,
  },

  placeHrs: {
    color: '#fff',
    fontSize: 15,
    lineHeight: 20,
  },
  placeOpenTime: {
    fontSize: 16,
    lineHeight: 25,
    textAlignVertical: 'center',
    color: '#474747',
    fontWeight: theme.FONT_WEIGHT_LIGHT,
  },
  seeAllButtonLabel: {
    color: theme.PRIMARY_COLOR,
    textTransform: 'none',
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 21,
    marginRight: 0,
  },
  editMenuTitle: {
    color: '#0065AB',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    fontSize: 16,
    fontFamily: 'Roboto',
    lineHeight: 21,
  },
  editMenuDescription: {
    color: '#4F4F4F',
    fontWeight: theme.FONT_WEIGHT_LIGHT,
    fontSize: 12,
    fontFamily: 'Roboto',
    lineHeight: 16,
  },
  editMenuCards: {
    borderRadius: 8,
    elevation: 1,
    marginBottom: 10,
  },
  editMenuIcon: {
    height: 40,
    width: 40,
    borderRadius: 12,
    marginRight: 5,
  },
  settingsContainer: {
    padding: 16,
  },
  editMenuItemTitle: {
    color: '#4F4F4F',
    fontSize: 16,
    lineHeight: 21,
    marginLeft: -19,
  },
  editMenuSettingsText: {
    color: '#4F4F4F',
    fontSize: 16,
    fontFamily: 'Roboto',
    lineHeight: 21,
  },
  documentsListHeading: {
    color: '#858585',
    fontSize: 14,
    fontFamily: 'Roboto',
    lineHeight: 19,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textTransform: 'uppercase',
  },
  businessName: {
    color: '#4f4f4f',
    fontSize: 18,
    fontFamily: 'Roboto',
    lineHeight: 24,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    padding: 15,
  },
  documentsName: {
    color: theme.PRIMARY_COLOR,
    fontSize: 18,
    fontFamily: 'Roboto',
    lineHeight: 24,
    padding: 15,
  },
  businessAccountInfoContainer: {
    marginTop: 30,
    marginLeft: 30,
    marginRight: 30,
  },
  deactivateButton: {
    borderColor: '#DD0022',
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 25,
    marginTop: 30,
  },
  deactivateButtonLabel: {
    color: '#DD0022',
    fontSize: 16,
    fontFamily: 'Roboto',
    lineHeight: 21,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  legalText: {
    textAlign: 'center',
    color: '#333333',
    fontSize: 14,
    fontFamily: 'Roboto',
    lineHeight: 24,
  },
  tableLabel: {
    // textAlign: 'center',
    color: '#aaaaaa',
    fontSize: 16,
    fontFamily: 'Roboto',
    lineHeight: 24,
  },
  tableValue: {
    color: '#3C3C3C',
    fontSize: 16,
    fontFamily: 'Roboto',
    lineHeight: 24,
    paddingTop: 30,
    paddingLeft: 15,
    paddingTop: 15,
    paddingBottom: 15,
  },
  tableContainer: {
    flexDirection: 'row',
    borderBottomColor: '#DEDEDE',
    borderBottomWidth: 1,
  },
  tableLabelContainer: {width: '40%', paddingTop: 15, paddingBottom: 15},
  formFieldLabel: {
    color: '#858585',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textTransform: 'uppercase',
    marginTop: 15,
    marginBottom: 5,
  },

  accountManagementText: {
    color: '#4F4F4F',
    fontSize: 16,
    lineHeight: 21,
    fontFamily: 'Roboto',
    textAlign: 'center',
  },
  accountManagementName: {
    color: theme.PRIMARY_COLOR,
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Roboto',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textAlign: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  editAccountInfoText: {
    color: '#4F4F4F',
    fontSize: 14,
    lineHeight: 24,
    fontFamily: 'Roboto',
  },
  submitButtonLabel: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    marginLeft: 20,
    marginRight: 20,
  },
  fieldHeadings: {
    fontSize: 13,
    color: '#939393',
    lineHeight: 20,
    marginTop: 10,
    marginLeft: 20,
  },
  listItem: {
    width: '90%',
    marginLeft: 20,
    padding: 10,
    borderRadius: 5,
    borderColor: '#efefef',
    borderWidth: 1,
    backgroundColor: '#fff',
  },
  fieldsValue: {
    fontSize: 16,
    color: '#474747',
    lineHeight: 21,
  },
  clientTypeListItem: {
    width: '90%',
    marginLeft: 20,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#fff',
    marginBottom: 10,
    marginTop: 10,
    height: 60,
    elevation: 1,
    textAlign: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'center',
  },
  clientTypeListTitle: {
    fontSize: 18,
    color: '#404040',
    lineHeight: 27,
  },
  updateButtonLable: {
    fontSize: 18,
    paddingBottom: 5,
    paddingTop: 5,
    textTransform: 'none',
  },
  updateButtonContainer: {
    alignItems: 'center',
    marginTop: 40,
  },
  updateButton: {
    backgroundColor: theme.PRIMARY_COLOR,
    borderRadius: 10,
    width: '50%',
  },
  successDialogHeading: {
    fontSize: 18,
    color: theme.PRIMARY_COLOR,
    textAlign: 'center',
    marginTop: 20,
  },
  successButton: {
    backgroundColor: theme.PRIMARY_COLOR,
    borderRadius: 10,
    width: 200,
    marginBottom: 20,
  },
  successButtonLable: {
    fontSize: 18,
    paddingBottom: 10,
    paddingTop: 10,
    textTransform: 'none',
  },
  addNewDataHeading: {
    fontSize: 24,
    lineHeight: 32,
    color: theme.PRIMARY_COLOR,
    textAlign: 'center',
  },
  addNewDataDesc: {
    fontSize: 14,
    lineHeight: 24,
    color: '#474747',
    fontFamily: 'Roboto',
    textAlign: 'center',
    paddingTop: 15,
  },
  submitButton: {
    borderRadius: 25,
    paddingLeft: 15,
    paddingRight: 15,
  },
  closeIcon: {
    textAlign: 'right',
    paddingRight: 10,
    paddingTop: 10,
  },
  drawerContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    elevation: 2,
    borderTopWidth: 0,
  },
  drawerHandler: {
    alignItems: 'center',
  },
  addLanguageText: {
    fontSize: 18,
    color: '#9f9e9e',
    textAlign: 'center',
    marginTop: 10,
  },
  personalInfoListItem: {
    fontSize: 18,
    color: '#404040',
  },
  selectedLanguageChip: {
    margin: 10,
    padding: 2,
    backgroundColor: '#5c5c5c',
    borderRadius: 20,
  },
  languagesContainer: {
    flexDirection: 'row',
    marginTop: 10,
    flex: 1,
    flexWrap: 'wrap',
    minHeight: 100,
  },
  selectedLanguageChipText: {
    color: '#fff',
    fontSize: 13,
  },
  fakeSheetCt: {
    backgroundColor: '#fff',
    width: '100%',
    position: 'absolute',
    bottom: 0,
    height: 180,
    // marginBottom: 10,
    // paddingBottom: 10,
  },
  addNewDataText: {
    fontSize: 14,
    lineHeight: 21,
    color: '#4f4f4f',
    marginLeft: 5,
  },
  successAddDialogText: {
    fontSize: 13,
    color: '#474747',
    textAlign: 'center',
    marginLeft: 20,
    marginRight: 20,
  },
  successAddDialogHeading: {
    fontSize: 13,
    color: '#474747',
    textAlign: 'center',
    margin: 20,
  },
  successAddButton: {
    backgroundColor: '#5ab949',
    borderRadius: 30,
    width: '40%',
    marginBottom: 20,
  },
  successAddButtonLable: {
    fontSize: 18,
    textTransform: 'none',
  },
  successButtonContainer: {
    alignItems: 'center',
    marginTop: 40,
  },
  holidaysText: {
    color: '#858585',
    fontSize: 12,
    fontFamily: 'Roboto',
    lineHeight: 16,
    textTransform: 'uppercase',
  },
  regularHoursText: {
    color: theme.PRIMARY_COLOR,
    fontSize: 14,
    fontFamily: 'Roboto',
    lineHeight: 19,
    textTransform: 'uppercase',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    marginTop: 5,
  },
  businessHoursCard: {
    marginTop: 10,
    borderRadius: 8,
    elevation: 2,
  },
  newScheduleText: {
    color: '#9F9F9F',
    fontSize: 9,
    lineHeight: 13,
    fontWeight: theme.FONT_WEIGHT_LIGHT,
    marginTop: 5,
  },
  noScheduleText: {
    color: '#B5B5B5',
    fontSize: 14,
    lineHeight: 19,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    marginTop: 5,
  },
  noScheduleCard: {
    borderWidth: 1,
    borderColor: '#DEDEDE',
    borderRadius: 8,
    marginTop: 10,
    elevation: 0,
  },
  dayName: {
    color: '#333333',
    fontSize: 16,
    lineHeight: 21,
    fontFamily: 'Roboto',
    marginTop: 5,
    width: '27%',
  },
  timeButton: {
    borderRadius: 20,
    marginRight: 10,
  },
  timeButtonLabel: {
    color: '#333333',
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Roboto',
  },
  addScheduleButtonLabel: {
    color: theme.PRIMARY_COLOR,
    fontSize: 12,
    // lineHeight: 16,
    fontFamily: 'Roboto',
    textTransform: 'none',
  },
  closedRedText: {
    color: '#FF0000',
    fontSize: 10,
    // lineHeight: 13,
    fontFamily: 'Roboto',
  },
  closedText: {
    color: '#B5B5B5',
    fontSize: 10,
    lineHeight: 13,
    fontFamily: 'Roboto',
  },

  addBusinessHoursText: {
    color: '#b5b5b5',
    fontSize: 12,
    // lineHeight: 16,
    fontFamily: 'Roboto',
    textTransform: 'none',
  },
  listItemDay: {
    color: '#858585',
    fontSize: 16,
    lineHeight: 21,
    fontFamily: 'Roboto',
  },
  updateButton: {
    borderColor: '#54B948',
    borderRadius: 25,
  },
  updateButtonLabel: {
    color: '#54B948',
    fontSize: 16,
    lineHeight: 21,
    fontFamily: 'Roboto',
    marginVertical: 5,
  },
  listItemClosedDay: {
    color: '#EF5E5E',
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Roboto',
    fontStyle: 'italic',
  },
  noRatingText: {
    color: '#E5E3E3',
    fontSize: 28,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textAlign: 'center',
  },
  ratingsCard: {
    marginBottom: 16,
    elevation: 2,
    borderRadius: 10,
    minHeight: 112,
    padding: 16,
    margin: 5,
  },
  reviewCount: {
    fontSize: 18,
    fontWeight: theme.FONT_WEIGHT_LIGHT,
    color: '#4F4F4F',
    lineHeight: 27,
  },
  reviewContent: {
    fontSize: 12,
    color: '#8F8F8F',
    fontFamily: 'Roboto',
    lineHeight: 16,
    marginTop: 10,
  },
  username: {
    fontSize: 14,
    color: '#616161',
    lineHeight: 21,
    marginTop: 20,
    marginLeft: 8,
  },
  time: {
    fontSize: 12,
    color: '#5D5D5D',
    lineHeight: 18,
    marginLeft: 2,
  },
  swipeText: {
    fontSize: 14,
    color: '#fff',
    lineHeight: 21,
  },
  swipeLeftActions: {
    justifyContent: 'center',
    minHeight: 112,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    marginRight: -20,
    elevation: 2,
    paddingLeft: 15,
    margin: 5,
  },
  reportedRedText: {
    fontSize: 14,
    color: '#EF5E5E',
    lineHeight: 19,
    fontFamily: 'Roboto',
    fontWeight: theme.FONT_WEIGHT_LIGHT,
  },
  optionsText: {
    fontSize: 16,
    color: '#B5B5B5',
    lineHeight: 40,
  },
  SelectedOptionText: {
    fontSize: 18,
    color: '#4f4f4f',
    lineHeight: 40,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  aboutUsDesc: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 24,
    fontSize: 14,
    color: '#858585',
    fontFamily: 'Roboto',
  },
  amenityLabel: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 19,
    color: '#858585',
    fontFamily: 'Roboto',
    marginTop: 5,
    marginLeft: 5,
    width: 150,
    textTransform: 'capitalize',
    textAlignVertical: 'center',
  },
  amenityValue: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 19,
    color: '#4F4F4F',
    fontFamily: 'Roboto',
    marginTop: 5,
    flexWrap: 'wrap',
    textAlignVertical: 'center',
  },
  mapImage: {
    width: '100%',
    height: 208,
    borderRadius: 8,
  },
  ratingsCardStyle2: {
    marginBottom: 16,
    elevation: 2,
    borderRadius: 10,
    minHeight: 112,
    padding: 16,
  },
  reviewCount: {
    fontSize: 18,
    fontWeight: theme.FONT_WEIGHT_LIGHT,
    color: '#4F4F4F',
    lineHeight: 27,
  },
  reviewContent: {
    fontSize: 12,
    color: '#8F8F8F',
    fontFamily: 'Roboto',
    lineHeight: 16,
    marginTop: 10,
  },
  username: {
    fontSize: 14,
    color: '#616161',
    lineHeight: 21,
    marginTop: 20,
    marginLeft: 8,
  },
  time: {
    fontSize: 12,
    color: '#5D5D5D',
    lineHeight: 18,
    marginLeft: 2,
  },
  loadMoreLabel: {
    color: theme.PRIMARY_COLOR,
    textTransform: 'none',
  },
  deleteButton: {
    borderColor: '#E20000',
    backgroundColor: '#fff',
    borderRadius: 24,
    borderWidth: 1,
    width: '45%',
  },
  deleteButtonLabel: {
    fontSize: 17,
    color: '#E20000',
    lineHeight: 26,
    marginVertical: 3,
  },
  cancelButton: {
    borderColor: '#474747',
    borderWidth: 1,
    backgroundColor: '#fff',
    borderRadius: 24,
    width: '45%',
  },
  cancelButtonLabel: {
    fontSize: 17,
    color: '#474747',
    lineHeight: 26,
    marginVertical: 3,
  },
});

export default styles;
