import {StyleSheet} from 'react-native';
import theme from './theme.style';

const styles = StyleSheet.create({
  rootContainer: {
    paddingTop: 20,
    paddingBottom: 51,
    paddingLeft: 16,
    paddingRight: 16,
  },
  modalTitle: {
    color: '#4F4F4F',
    lineHeight: 37,
    fontSize: 28,
    fontFamily: 'Roboto',
    textAlign: 'center',
    paddingTop: 20,
    paddingBottom: 20,
  },
  stepContainer: {
    flexDirection: 'row',
    paddingBottom: 15,
    // margin: 15,
  },
  stepCircle: {
    height: 56,
    width: 56,
    borderWidth: 1,
    borderColor: '#b5b5b5',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
  },
  stepLabel: {
    color: theme.PRIMARY_COLOR,
    lineHeight: 37,
    fontSize: 28,
    fontFamily: 'Roboto',
  },
  stepTitle: {
    color: theme.PRIMARY_COLOR,
    lineHeight: 24,
    fontSize: 18,
    fontFamily: 'Roboto',
    paddingLeft: 10,
    paddingRight: 16,
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  stepDescription: {
    color: '#858585',
    lineHeight: 24,
    fontSize: 14,
    fontFamily: 'Roboto',
    paddingLeft: 10,
    paddingRight: 16,
    flexWrap: 'wrap',
    flexDirection: 'row',
    width: '50%',
  },
  setupStartButton: {
    height: 48,
    borderRadius: 24,
    width: '60%',
    marginTop: 20,
  },
  setupStartButtonLabel: {
    lineHeight: 24,
    fontSize: 18,
    fontFamily: 'Roboto',
    textTransform: 'capitalize',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },

  addNewBusinessText: {
    lineHeight: 24,
    fontSize: 24,
    color: '#b5b5b5',
    textAlign: 'center',
  },
  addBusinessCard: {
    height: 72,
    borderRadius: 15,
    elevation: 2,
    marginTop: 20,
    marginLeft: 16,
    marginRight: 16,
  },
  addNewBusinessButtonText: {
    lineHeight: 24,
    fontSize: 18,
    color: theme.PRIMARY_COLOR,
    marginLeft: 15,
    letterSpacing: 0,
  },
  setupHeadings: {
    lineHeight: 27,
    fontSize: 18,
    color: theme.PRIMARY_COLOR,
    textAlign: 'center',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  setupSubHeadings: {
    lineHeight: 23,
    fontSize: 15,
    color: '#47474760',
    marginTop: 30,
    textAlign: 'center',
  },
  dropdownButton: {
    borderRadius: 25,
    height: 48,
    borderColor: '#3597EC',
    borderWidth: 1,
    marginTop: 30,
    width: '100%',
    flexDirection: 'row',
  },
  dropdownButtonLabel: {
    lineHeight: 25,
    fontSize: 16,
    color: '#939393',
    paddingLeft: 20,
    marginVertical: 10,
  },
  nextButton: {
    // height: 56,
    width: '45%',
    borderRadius: 30,
    justifyContent: 'center',
  },
  nextButtonLabel: {
    lineHeight: 27,
    fontSize: 18,
    color: '#fff',
    textTransform: 'none',
  },
  exitButton: {
    marginTop: 30,
  },
  exitButtonLabel: {
    lineHeight: 27,
    fontSize: 18,
    color: '#47474736',
    textTransform: 'none',
  },
  countryList: {
    // width: '100%',
  },
  searchOverlay: {
    flex: 1,
    position: 'absolute',
    left: -60,
    top: -120,
    opacity: 0.1,
    backgroundColor: '#fff',
  },
  searchListView: {
    backgroundColor: '#fff',
    minHeight: 20,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    height: 360,
    borderColor: theme.PRIMARY_COLOR,
    borderWidth: 1,
  },

  businessNameDivider: {
    backgroundColor: theme.PRIMARY_COLOR,
    height: 1,
  },
  businessNameField: {
    marginTop: 30,
    marginLeft: 20,
    marginRight: 20,
  },
  businessNameSubheader: {
    lineHeight: 18,
    fontSize: 13,
    color: '#4f4f4f',
    flexWrap: 'wrap',
    flexDirection: 'row',
    width: '100%',
    padding: 16,
  },
  businessNameSearchField: {
    paddingLeft: 20,
    borderWidth: 1,
    borderColor: theme.PRIMARY_COLOR,
    borderRadius: 30,
    backgroundColor: '#fff',
    height: 40,
  },
  claimButtonLabel: {
    lineHeight: 20,
    fontSize: 13,
    textTransform: 'capitalize',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  businessNameListTitle: {
    lineHeight: 21,
    fontSize: 16,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    textTransform: 'capitalize',
    color: '#4F4F4F',
    paddingLeft: 5,
  },
  businessNameListDesc: {
    lineHeight: 19,
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: theme.FONT_WEIGHT_LIGHT,
    color: '#474747',
    paddingLeft: 5,
  },
  addImageText: {
    lineHeight: 25,
    fontSize: 16,
    color: theme.PRIMARY_COLOR,
  },
  shopIconContainer: {
    height: 160,
    width: 160,
    borderRadius: 80,
    backgroundColor: '#61C2FF',
    borderColor: '#fff',
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    marginTop: 30,
    elevation: 2,
  },
  mapImage: {
    // width: '90%',
    height: 176,
    marginTop: 20,
  },
  areaText: {
    lineHeight: 16,
    fontSize: 12,
    fontFamily: 'Roboto',
    color: '#4f4f4f',
    marginRight: 20,
    marginTop: 5,
  },
  shopIconContainerStep5: {
    height: 96,
    width: 96,
    borderRadius: 80,
    backgroundColor: '#61C2FF',
    borderColor: theme.PRIMARY_COLOR,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    marginTop: 30,
    elevation: 2,
  },
  step5PlaceName: {
    lineHeight: 21,
    fontSize: 16,
    fontFamily: 'Roboto',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    color: '#4f4f4f',
  },
  step5Location: {
    lineHeight: 19,
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    color: '#858585',
    marginTop: 3,
  },
  authorizedText: {
    lineHeight: 21,
    fontSize: 16,
    fontFamily: 'Roboto',
    color: '#4F4F4F',
    marginTop: 50,
    marginLeft: 16,
  },
  authorizedSwitch: {
    marginTop: 50,
    marginRight: 16,
  },
  plusTextStep6: {
    lineHeight: 21,
    fontSize: 14,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    color: '#47474786',
    marginTop: 10,
    // textAlign: 'center',
  },
  verificationButton: {
    // height: 56,
    width: '45%',
    borderRadius: 30,
    justifyContent: 'center',
    backgroundColor: '#54B948',
  },
  verificationButtonLabel: {
    lineHeight: 27,
    fontSize: 18,
    color: '#fff',
    textTransform: 'capitalize',
  },
  linkText: {
    lineHeight: 21,
    fontSize: 14,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    color: theme.PRIMARY_COLOR,
    fontFamily: 'Roboto',
  },
  registrationText: {
    lineHeight: 21,
    fontSize: 16,
    color: '#4F4F4F',
    fontFamily: 'Roboto',
    marginLeft: 20,
  },
  documentUploadCard: {
    borderRadius: 8,
    elevation: 2,
    marginTop: 30,
    marginLeft: 16,
    marginRight: 16,
  },
  registrationSubText: {
    lineHeight: 16,
    fontSize: 12,
    color: '#858585',
    fontFamily: 'Roboto',
    marginLeft: 20,
  },
  uploadButton: {
    alignItems: 'flex-end',
    borderLeftWidth: 1,
    borderLeftColor: '#DEDEDE',
    marginLeft: 20,
    justifyContent: 'center',
  },
  uploadButtonLabel: {
    color: theme.PRIMARY_COLOR,
    textTransform: 'none',
    lineHeight: 19,
    fontSize: 14,
    letterSpacing: 0,
  },
  expirationField: {
    paddingLeft: 20,
    borderWidth: 1,
    borderColor: '#b5b5b5',
    borderRadius: 30,
    backgroundColor: '#fff',
  },
  calendarIcon: {
    position: 'absolute',
    right: 18,
    top: 12,
  },
  verificationButtonDisabled: {
    // height: 56,
    width: '45%',
    borderRadius: 30,
    justifyContent: 'center',
    borderColor: '#54B948',
    borderWidth: 1,
  },
  nextButtonDisable: {
    // height: 56,
    width: '45%',
    borderRadius: 30,
    justifyContent: 'center',
    borderColor: theme.PRIMARY_COLOR,
    borderWidth: 1,
  },
  qongfuBusinessHeadings: {
    lineHeight: 48,
    fontSize: 32,
    color: theme.PRIMARY_COLOR,
    textAlign: 'center',
  },
  qongfuBusinessSubHeadings: {
    lineHeight: 24,
    fontSize: 16,
    color: '#4F4F4F',
    marginTop: 30,
    textAlign: 'center',
  },
  locationConfirmButton: {
    position: 'absolute',
    bottom: 40,
    left: 70,
  },
  confirmButton: {
    backgroundColor: theme.PRIMARY_COLOR,
    borderRadius: 30,
    width: 250,
  },
  confirmButtonDisable: {
    backgroundColor: theme.SECONDARY_COLOR,
    borderRadius: 30,
    width: 250,
  },
  confirmButtonLable: {
    fontSize: 18,
    paddingBottom: 5,
    paddingTop: 5,
    textTransform: 'none',
  },
  confirmButtonLableDisable: {
    fontSize: 18,
    paddingBottom: 5,
    paddingTop: 5,
    color: '#fff',
    textTransform: 'none',
  },
  searchField: {
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
  },
  searchFieldText: {
    backgroundColor: '#fff',
    // borderRadius: 30,
  },
  updateButtonContainer: {
    alignItems: 'center',
    marginTop: 40,
  },
  successDialogHeading: {
    fontSize: 18,
    color: theme.PRIMARY_COLOR,
    textAlign: 'center',
    marginTop: 20,
  },
  successButton: {
    backgroundColor: theme.PRIMARY_COLOR,
    borderRadius: 10,
    width: 200,
    marginBottom: 20,
  },
  successButtonLable: {
    fontSize: 18,
    paddingBottom: 10,
    paddingTop: 10,
    textTransform: 'none',
  },
  countryFlag: {
    position: 'absolute',
    right: -50,
    top: 6,
    zIndex: 99,
    backgroundColor: '#fff',
    height: 55,
    width: 55,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
