import {StyleSheet} from 'react-native';
import theme from './theme.style';

const styles = StyleSheet.create({
  addNewMediaText: {
    lineHeight: 30,
    fontSize: 28,
    color: '#E5E3E3',
    textAlign: 'center',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  uploadMediaCard: {
    height: 72,
    borderRadius: 15,
    elevation: 1,
    marginTop: 20,
    marginLeft: 16,
    marginRight: 16,
    marginBottom: 10,
  },
  uploadMediaText: {
    fontSize: 15,
    lineHeight: 20,
    color: theme.PRIMARY_COLOR,
    marginLeft: 15,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  imageContainer: {
    flexDirection: 'column',
    height: 232,
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
  },
  captionLabel: {
    fontSize: 12,
    lineHeight: 16,
    color: '#4F4F4F',
    marginBottom: 10,
    fontFamily: 'Roboto',
  },
  postButton: {
    borderRadius: 25,
    width: '60%',
    marginTop: 30,
  },
  postButtonLabel: {
    fontSize: 16,
    lineHeight: 25,
    textTransform: 'none',
  },
  addButton: {
    borderRadius: 25,
    borderColor: theme.PRIMARY_COLOR,
    width: '40%',
    marginTop: 15,
  },
  addButtonLabel: {
    fontSize: 16,
    lineHeight: 25,
    textTransform: 'none',
  },
  addingPostText: {
    fontSize: 16,
    lineHeight: 18,
    color: '#B5B5B5',
    textAlign: 'center',
    marginTop: 15,
    // fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  arrowButton: {
    height: 64,
    backgroundColor: '#00000024',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 5,
    paddingRight: 5,
  },
  mediaImage: {
    height: 48,
    width: 48,
    borderRadius: 8,
    marginLeft: 5,
    position: 'relative',
  },
  addImageContainer: {
    height: 48,
    width: 48,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#dedede',
    marginLeft: 5,
    position: 'relative',
    zIndex: 1,
    marginRight: 10,
  },
  selectedMediaImage: {
    height: 48,
    width: 48,
    borderRadius: 8,
    marginLeft: 5,
    borderColor: theme.PRIMARY_COLOR,
    borderWidth: 1,
  },
  videoIcon: {
    elevation: 3,
    borderRadius: 30,
    height: 59,
    width: 59,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unpublishedText: {
    fontSize: 14,
    lineHeight: 19,
    color: '#4F4F4F',
    marginLeft: 5,
    fontFamily: 'Roboto',
  },
  deleteHeading: {
    fontSize: 18,
    color: '#47474786',
    lineHeight: 27,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textAlign: 'center',
    marginBottom: 10,
  },
  deleteText: {
    fontSize: 13,
    color: '#47474760',
    lineHeight: 20,
    textAlign: 'center',
  },
  deleteButton: {
    borderColor: '#E20000',
    backgroundColor: '#fff',
    borderRadius: 24,
    borderWidth: 1,
    width: '45%',
  },
  deleteButtonLabel: {
    fontSize: 17,
    color: '#E20000',
    lineHeight: 26,
  },
  cancelButton: {
    borderColor: '#474747',
    borderWidth: 1,
    backgroundColor: '#fff',
    borderRadius: 24,
    width: '45%',
  },
  cancelButtonLabel: {
    fontSize: 17,
    color: '#474747',
    lineHeight: 26,
  },
  deleteText: {
    color: '#FF0000',
    textTransform: 'uppercase',
    fontSize: 14,
    fontFamily: 'Roboto',
    lineHeight: 19,
    textAlign: 'center',
  },
  deleteContainer: {
    width: 100,
    // height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F7F7F7',
    zIndex: 1,
    borderColor: '#FF0000',
    borderStyle: 'dashed',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
  },
});

export default styles;
