import {StyleSheet} from 'react-native';
import theme from './theme.style';

const styles = StyleSheet.create({
  mediaCarouselContainer: {
    // margin: 16,
  },
  mediaCarouselTitle: {
    fontSize: 24,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    color: '#858585',
    marginBottom: 18,
  },
  seeAllButtonLabel: {
    color: theme.PRIMARY_COLOR,
    textTransform: 'none',
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 21,
    // marginRight: 0,
  },
  mediaCarouselCardCollapse: {
    borderRadius: 10,
    // minHeight: 328,
  },
  mediaCarouselCardExpand: {
    borderRadius: 10,
  },
  mediaCarouselContent: {
    fontSize: 14,
    color: '#858585',
    fontFamily: 'Roboto',
    lineHeight: 16,
  },
  mediaCarouselTime: {
    fontSize: 12,
    lineHeight: 16,
    textAlignVertical: 'center',
    color: '#B5B5B5',
    fontFamily: 'Roboto',
  },
  mediaCardCover: {
    height: 184,
    width: '100%',
    borderRadius: 4,
  },
  sliderDot: {
    width: 8,
    height: 8,
    borderRadius: 10,
    marginHorizontal: 5,
    backgroundColor: theme.PRIMARY_COLOR,
    borderColor: '#ababab',
    borderWidth: 1,
    marginTop: -22,
  },
  inactiveSliderDot: {
    width: 8,
    height: 8,
    borderRadius: 10,
    marginHorizontal: 5,
    marginTop: -22,
    backgroundColor: '#f8fcff',
    borderColor: '#ababab',
    borderWidth: 1,
  },
  dotContainer: {},
  moreButton: {
    // color: theme.PRIMARY_COLOR,
    fontSize: 12,
    fontFamily: 'Roboto',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    marginVertical: 0,
  },
  sections: {
    padding: 16,
  },
  mediaCarouselUnpublishedTime: {
    fontSize: 12,
    lineHeight: 16,
    textAlignVertical: 'center',
    color: '#333333',
    fontFamily: 'Roboto',
  },
  optionsText: {
    fontSize: 16,
    color: '#B5B5B5',
    lineHeight: 40,
  },
  SelectedOptionText: {
    fontSize: 18,
    color: '#4f4f4f',
    lineHeight: 40,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  deleteHeading: {
    fontSize: 18,
    color: '#47474786',
    lineHeight: 27,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textAlign: 'center',
    marginBottom: 10,
  },
  deleteText: {
    fontSize: 13,
    color: '#47474760',
    lineHeight: 20,
    textAlign: 'center',
  },
  deleteButton: {
    borderColor: '#E20000',
    backgroundColor: '#fff',
    borderRadius: 24,
    borderWidth: 1,
    width: '45%',
  },
  deleteButtonLabel: {
    fontSize: 17,
    color: '#E20000',
    lineHeight: 26,
  },
  cancelButton: {
    borderColor: '#474747',
    borderWidth: 1,
    backgroundColor: '#fff',
    borderRadius: 24,
    width: '45%',
  },
  cancelButtonLabel: {
    fontSize: 17,
    color: '#474747',
    lineHeight: 26,
  },
  reportTitle: {
    fontSize: 14,
    color: '#4F4F4F',
    lineHeight: 21,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    marginTop: 5,
  },
  reportContent: {
    fontSize: 12,
    color: '#858585',
    lineHeight: 18,
    marginLeft: 35,
    marginTop: -9,
  },
  reportHeading: {
    fontSize: 24,
    color: '#4f4f4f',
    lineHeight: 35,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textAlign: 'center',
    marginBottom: 15,
    marginTop: 15,
  },
  reportButton: {
    borderRadius: 24,
    borderWidth: 1,
    width: '60%',
    marginBottom: 20,
    marginTop: 20,
  },
  reportButtonLabel: {
    fontSize: 17,
    lineHeight: 26,
    textTransform: 'none',
  },
  reportCancelButton: {
    fontSize: 18,
    color: '#858585',
    lineHeight: 24,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    fontFamily: 'Roboto',
    textTransform: 'none',
  },
  errorText: {
    fontSize: 13.6,
    marginLeft: 10,
    color: '#ff2121',
    paddingTop: 0,
  },
  emptySection: {
    fontSize: 20,
    color: '#e5e3e3',
    margin: 40,
    textAlign: 'center',
  },
});

export default styles;
