import {StyleSheet} from 'react-native';
import theme from './theme.style';

const styles = StyleSheet.create({
  topBarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    elevation: 2,
    backgroundColor: '#fff',
  },
  topBarTitle: {
    fontSize: 18,
    color: theme.PRIMARY_COLOR,
  },
  locationIcon: {
    marginRight: 10,
    marginTop: 2,
  },
  titleRow: {
    flexDirection: 'row',
  },
  imageContainer: {
    flexDirection: 'column',
    height: 200,
    position: 'relative',
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
  },
  placeCardDesc: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  placeName: {
    fontSize: 20,
    color: '#333333',
    marginTop: 2,
  },
  textLabelMargin: {
    marginLeft: 8,
  },
  placeOpen: {
    fontSize: 14,
    color: '#54b948',
  },
  placeClose: {
    fontSize: 14,
    color: 'red',
  },
  time: {
    fontWeight: '400',
    fontSize: 14,
    color: '#5d5d5d',
  },
  location: {
    fontWeight: '400',
    fontSize: 14,
    color: '#5d5d5d',
  },
  city: {
    fontWeight: '400',
    fontSize: 14,
    color: '#ababab',
  },
  headerTabBtn: {
    backgroundColor: '#fff',
    borderRadius: 0,
  },
  headerTabBtnActive: {
    borderBottomColor: theme.PRIMARY_COLOR,
    borderBottomWidth: 2,
  },
  headerTabBtnLabelActive: {
    color: theme.PRIMARY_COLOR,
    fontSize: 16,
    textTransform: 'none',
  },
  headerTabBtnLabelInActive: {
    color: theme.SECONDARY_COLOR,
    fontSize: 16,
    textTransform: 'none',
  },
  placeDetailContent: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  aboutUsTitle: {
    fontSize: 24,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    color: '#858585',
    marginBottom: 18,
  },
  aboutUsDesc: {
    fontSize: 14,
    fontFamily: 'Roboto',
    color: '#474747',
  },
  lifeStyleTitle: {
    fontSize: 28,
    color: '#5d5d5d',
  },
  ratingContainer: {
    position: 'absolute',
    bottom: 2,
    right: 0,
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  starRatingContain: {
    backgroundColor: '#4f4d4b82',
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    paddingLeft: 10,
    paddingRight: 3,
  },
  ratingStyle: {
    color: '#efefef',
    fontSize: 18,
    paddingLeft: 3,
    paddingRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
    height: 26,
    backgroundColor: '#4f4d4b82',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  lifestyleAndQongfuContain: {
    flexDirection: 'row',
    marginTop: 10,
    flex: 1,
    flexWrap: 'wrap',
  },
  lifestyleChip: {
    width: 120,
    borderRadius: 10,
    marginRight: 20,
  },
  lifestyleChipText: {
    color: '#fff',
    marginLeft: 10,
    fontWeight: 'bold',
  },
  qongfuChip: {
    width: 160,
    marginRight: 20,
    marginTop: 20,
  },
  qongfuChipText: {
    color: '#fff',
    marginLeft: 20,
  },
  contentSpace: {
    marginTop: 16,
    marginBottom: 16,
  },
  amenityLabel: {
    fontSize: 14,
    fontFamily: 'Roboto',
    color: '#858585',
    lineHeight: 16,
  },
  amenityInfo: {
    fontSize: 16,
    color: theme.SECONDARY_COLOR,
  },
  rateUsBtn: {
    color: theme.PRIMARY_COLOR,
    borderRadius: 10,
    borderColor: theme.PRIMARY_COLOR,
    justifyContent: 'center',
  },
  rateUsBtnLabel: {
    color: theme.PRIMARY_COLOR,
  },
  username: {
    fontSize: 16,
    color: '#474747',
    fontWeight: 'bold',
  },
  userLocation: {
    color: '#ababab',
    fontSize: 12,
  },
  ratingTitle: {
    fontSize: 16,
    color: '#5d5d5d',
    marginBottom: 10,
    marginTop: 10,
  },
  reviewTitle: {
    fontSize: 18,
    color: '#5d5d5d',
    marginBottom: 10,
    marginTop: 10,
  },
  ratingSub: {
    fontSize: 14,
    color: theme.SECONDARY_COLOR,
  },
  loadMoreLabel: {
    color: theme.PRIMARY_COLOR,
    textTransform: 'none',
  },
  inputAndroid: {
    fontSize: 30,
    paddingHorizontal: 10,
    paddingVertical: 0,
    borderWidth: 1,
    borderColor: theme.SECONDARY_COLOR,
    borderRadius: 35,
    color: '#000',
    paddingRight: 0,
    marginTop: 10,
    marginBottom: 10,
  },
  mediaTabSelectionTitle: {
    fontSize: 10,
    color: '#5d5d5d',
    marginTop: 20,
    fontWeight: 'bold',
  },
  mediaCardImage: {
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
  },
  mediaCardTitle: {
    fontSize: 14,
    color: '#5d5d5d',
    fontWeight: 'bold',
  },
  mediaCardDesc: {
    fontSize: 14,
    color: theme.SECONDARY_COLOR,
    paddingTop: 10,
    paddingBottom: 10,
  },
  mediaCardContent: {
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 10,
  },
  mediaTabHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 30,
  },
  mediaTabSelect: {
    height: 50,
    width: 130,
  },
  mediaCardContain: {
    marginBottom: 30,
  },
  headerContainer: {
    elevation: 1,
    marginBottom: 10,
    flexDirection: 'column',
  },
  headerLogoTab: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    position: 'relative',
  },
  headerLogoContain: {
    position: 'absolute',
    bottom: -15,
    left: 20,
  },
  headerLogo: {
    backgroundColor: '#fff',
  },
  headerStartIcon: {
    // marginRight: 20,
    // marginTop: 10,
  },
  headerPhoneIcon: {
    // position: 'absolute',
    // right: -140,
    // marginTop: 10,
  },
  weekScheduleMenu: {
    width: 370,
    borderRadius: 20,
    marginTop: 10,
  },
  weekScheduleListContain: {
    paddingLeft: 16,
    paddingRight: 16,
  },
  weekScheduleListContainActive: {
    backgroundColor: '#ecf7fd',
  },
  weekScheduleListText: {
    fontSize: 16,
    color: theme.SECONDARY_COLOR,
  },
  weekScheduleListTextActive: {
    fontSize: 16,
    color: '#5d5d5d',
    fontWeight: 'bold',
  },
  closeDay: {
    backgroundColor: '#ff0000',
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 10,
  },
  closeDayText: {
    color: '#fff',
    marginTop: 5,
    fontSize: 16,
    fontWeight: 'bold',
  },
  shareMenuListItem: {
    fontSize: 16,
    color: theme.SECONDARY_COLOR,
  },
  shareMenu: {
    width: 150,
    borderBottomLeftRadius: 20,
    marginTop: 30,
    marginLeft: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  callDialogBtnLabel: {
    fontSize: 17,
    color: theme.PRIMARY_COLOR,
    textTransform: 'none',
  },
  callDialogTitle: {
    textAlign: 'center',
    paddingTop: 10,
    paddingBottom: 10,
  },
  callDialogAction: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 10,
  },
  mediaTypeList: {
    width: 150,
    borderRadius: 20,
    marginTop: 10,
  },
  selectMediaContainer: {
    padding: 15,
    minWidth: 100,
  },
  qongfuHeading: {
    color: theme.PRIMARY_COLOR,
    fontSize: 24,
    textAlign: 'center',
    marginTop: 10,
  },
  qongfuDescription: {
    color: theme.SECONDARY_COLOR,
    fontSize: 14,
    textAlign: 'center',
    margin: 20,
  },
  textFieldLabels: {
    fontSize: 13,
    color: '#939393',
    marginLeft: 20,
    marginBottom: 10,
    marginTop: 10,
  },
  textInputField: {
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: '#ffffff',
    borderRadius: 30,
    borderColor: '#efefef',
    borderWidth: 1,
    textAlign: 'center',
  },
  updateButtonLable: {
    fontSize: 18,
    paddingBottom: 5,
    paddingTop: 5,
    textTransform: 'none',
  },
  updateButtonContainer: {
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 10,
  },
  updateButton: {
    backgroundColor: theme.PRIMARY_COLOR,
    borderRadius: 30,
    width: 250,
  },
  successDialogHeading: {
    fontSize: 18,
    color: theme.PRIMARY_COLOR,
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 30,
  },
  mapImage: {
    width: '100%',
    height: 180,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  placeLocation: {
    fontSize: 16,
    color: theme.SECONDARY_COLOR,
  },
  aboutUsTitleStyle2: {
    fontSize: 24,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    lineHeight: 35,
    color: '#858585',
    textTransform: 'capitalize',
  },
  aboutUsDescCollapseStyle2: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 24,
    color: '#858585',
    fontFamily: 'Roboto',
    height: 97,
  },
  aboutUsDescExpandStyle2: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 24,
    color: '#858585',
    fontFamily: 'Roboto',
  },
  moreButton: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 24,
    color: theme.PRIMARY_COLOR,
    fontFamily: 'Roboto',
    textTransform: 'uppercase',
    textAlign: 'right',
  },
  amenityLabelStyle2: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 19,
    color: '#858585',
    fontFamily: 'Roboto',
    marginTop: 5,
    marginLeft: 5,
    width: 150,
    textTransform: 'capitalize',
    textAlignVertical: 'center',
  },
  amenityValueStyle2: {
    fontSize: theme.FONT_SIZE_SMALL,
    lineHeight: 19,
    color: '#4F4F4F',
    fontFamily: 'Roboto',
    marginTop: 5,
    flexWrap: 'wrap',
    textAlignVertical: 'center',
  },
  mapImageSyle2: {
    width: '100%',
    height: 208,
    borderRadius: 8,
  },
  placeLocationStyle2: {
    fontSize: theme.FONT_SIZE_SMALL,
    fontFamily: 'Roboto',
    lineHeight: 24,
    color: '#474747',
  },
  lifestyleStyle2: {
    fontSize: 12,
    fontFamily: 'Roboto',
    lineHeight: 16,
    marginRight: 10,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
    textTransform: 'capitalize',
  },
  lifestyleContainerStyle2: {
    flexDirection: 'row',
    marginBottom: 10,
    flex: 1,
    flexWrap: 'wrap',
  },
  moreButtonStyle2: {
    fontSize: 12,
    fontFamily: 'Roboto',
    lineHeight: 16,
    color: '#b5b5b5',
    fontStyle: 'italic',
    textAlign: 'right',
  },
  headerPhoneIconStyle2: {
    position: 'absolute',
    right: -120,
    marginTop: 10,
  },
  placeOpenContainerStyle2: {
    backgroundColor: '#54B948',
    textTransform: 'uppercase',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
  },
  placeOpenStyle2: {
    fontSize: 15,
    color: '#fff',
    letterSpacing: 0,
    fontWeight: theme.FONT_WEIGHT_LIGHT,
  },
  placeClosedContainerStyle2: {
    backgroundColor: 'red',
    textTransform: 'uppercase',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  ratingsCardStyle2: {
    marginBottom: 16,
    elevation: 2,
    borderRadius: 10,
    minHeight: 112,
    padding: 16,
  },
  reviewCountStyle2: {
    fontSize: 18,
    fontWeight: theme.FONT_WEIGHT_LIGHT,
    color: '#4F4F4F',
    lineHeight: 27,
  },
  reviewContentStyle2: {
    fontSize: 12,
    color: '#8F8F8F',
    fontFamily: 'Roboto',
    lineHeight: 16,
    marginTop: 10,
  },
  usernameStyle2: {
    fontSize: 14,
    color: '#616161',
    lineHeight: 21,
    marginTop: 20,
    marginLeft: 8,
  },
  timeStyle2: {
    fontSize: 12,
    color: '#5D5D5D',
    lineHeight: 18,
    marginLeft: 2,
  },
  imageContainerStyle2: {
    flexDirection: 'column',
    height: 221,
    position: 'relative',
    // borderWidth: 1,
    // borderColor: '#707070',
  },
  placeNameStyle2: {
    fontSize: 24,
    color: '#4F4F4F',
    lineHeight: 35,
    marginTop: 10,
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  shieldIcon: {
    marginTop: 10,
  },
  placeOpenTimeStyle2: {
    fontSize: 16,
    lineHeight: 25,
    textAlignVertical: 'center',
    color: '#474747',
    fontWeight: theme.FONT_WEIGHT_LIGHT,
  },
  placeCityStyle2: {
    fontSize: 14,
    lineHeight: 19,
    textAlignVertical: 'center',
    color: '#474747',
    marginLeft: 3,
  },
  ratingsStyle2: {
    color: '#56BAFF',
    fontSize: 16,
    paddingLeft: 3,
    paddingRight: 10,
    paddingTop: 2,
    height: 22,
    backgroundColor: '#4f4d4b82',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  closeDayTextStyle2: {
    color: '#fff',
    fontSize: 17,
    lineHeight: 26,
    textTransform: 'uppercase',
    fontWeight: theme.FONT_WEIGHT_MEDIUM,
  },
  closeDayStyle2: {
    backgroundColor: '#ff0000',
    paddingLeft: 7,
    paddingRight: 7,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    height: 24,
  },
});

export default styles;
