import React from 'react';
import {View, Text, Linking} from 'react-native';
import PageLayout from '../../layout/PageLayout';
import styles from '../../styles/settings.style';
import {Paragraph} from 'react-native-paper';

const PrivacyPolicy = () => {
  const handleOpenLink = link => {
    let URL = '';
    if (link === 'qongfu') {
      URL = 'https://qongfu.com/';
    } else if (link === 'policyMaker') {
      URL = 'https://policymaker.io/';
    } else if (link === 'privacyPolicy') {
      URL = 'https://policymaker.io/privacy-policy';
    }
    Linking.openURL(URL).catch(err => console.error('An error occurred', err));
  };
  return (
    <PageLayout>
      <View style={styles.descriptionContainer}>
        <Text style={styles.descriptionHeading}>1. Introduction</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Welcome to{' '}
            <Text style={styles.descriptionBoldText}>
              Qongfu Technologies Co SPC.
            </Text>{' '}
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>
            Qongfu Technologies Co SPC{' '}
          </Text>
          <Text style={styles.descriptionText}>
            (“us”, “we”, or “our”) operates{' '}
          </Text>
          <Text
            style={styles.descriptionLinkText}
            onPress={() => handleOpenLink('qongfu')}>
            www.qongfu.com{' '}
          </Text>
          <Text style={styles.descriptionText}>
            (hereinafter referred to as{' '}
          </Text>
          <Text style={styles.descriptionBoldText}>“our services”). </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Our Privacy Policy governs your visit to{' '}
          </Text>
          <Text
            style={styles.descriptionLinkText}
            onPress={() => handleOpenLink('qongfu')}>
            www.qongfu.com,{' '}
          </Text>
          <Text style={styles.descriptionText}>
            and explains how we collect, safeguard and disclose information that
            results from your use of our services.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We use your data to provide and improve our services. By using our
            services, you agree to the collection and use of information in
            accordance with this policy. Unless otherwise defined in this
            Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms and Conditions.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>Our Terms and Conditions </Text>
          <Text style={styles.descriptionBoldText}>(“Terms”) </Text>
          <Text style={styles.descriptionText}>
            govern all use of our services and together with the Privacy Policy
            constitutes your agreement with us{' '}
          </Text>
          <Text style={styles.descriptionBoldText}>(“agreement”). </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>2. Definitions</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>
            OUR SERVICE (“our service”){' '}
          </Text>
          <Text style={styles.descriptionText}>
            means the www.qongfu.com website operated by Qongfu Technologies Co
            SPC and/or Qongfu’s Mobile App on iOS and Android.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>PERSONAL DATA </Text>
          <Text style={styles.descriptionText}>
            means data about a living individual who can be identified from
            those data (or from those and other information either in our
            possession or likely to come into our possession).
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>USAGE DATA </Text>
          <Text style={styles.descriptionText}>
            is data collected automatically either generated by the use of our
            services or from our services’ infrastructure itself (for example,
            the duration of a page visit).
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>COOKIES </Text>
          <Text style={styles.descriptionText}>
            are small files stored on your device (computer or mobile device).
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>DATA CONTROLLER </Text>
          <Text style={styles.descriptionText}>
            means a natural or legal person who (either alone or jointly or in
            common with other persons) determines the purposes for which and the
            manner in which any personal data are, or are to be, processed. For
            the purpose of this Privacy Policy, we are a Data Controller of your
            data.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>
            DATA PROCESSORS (OR SERVICE PROVIDERS){' '}
          </Text>
          <Text style={styles.descriptionText}>
            means any natural or legal person who processes the data on behalf
            of the Data Controller. We may use the services of various Service
            Providers (i.e. Google, Apple, etc) in order to process your data
            more effectively.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>DATA SUBJECT </Text>
          <Text style={styles.descriptionText}>
            is any living individual who is the subject of Personal Data.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionBoldText}>THE USER </Text>
          <Text style={styles.descriptionText}>
            is the individual using our services. The User corresponds to the
            Data Subject, who is the subject of Personal Data.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>
          3. Information Collection and Use
        </Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We collect several different types of information for various
            purposes to provide and improve our services to you.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>
          4. Types of Data Collected
        </Text>
        <Text style={styles.descriptionHeading}>Personal Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            While using our services, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you{' '}
            <Text style={styles.descriptionBoldText}>(“Personal Data”).</Text>{' '}
            Personally identifiable information may include, but is not limited
            to:
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>0.1. Email address</Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.2. First name and last name
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>0.3. Phone number</Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.4. Address, Country, State, Province, ZIP/Postal code, City
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.5. Cookies and Usage Data
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link or
            using the setting preferences provided on our website or mobile
            apps.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>Usage Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may also collect information that your browser sends whenever you
            visit our services or when you access our services by or through any
            device{' '}
          </Text>
          <Text style={styles.descriptionBoldText}>(“Usage Data”).</Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            This Usage Data may include information such as your computer’s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our services that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            When you access our services with a device, this Usage Data may
            include information such as the type of device you use, your device
            unique ID, the IP address of your device, your device operating
            system, the type of Internet browser you use, unique device
            identifiers and other diagnostic data.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>Location Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may use and store information about your location if you give us
            permission to do so{' '}
          </Text>
          <Text style={styles.descriptionBoldText}>(“Location Data”). </Text>
          <Text style={styles.descriptionText}>
            We use this data to provide the features of our services, as well as
            to improve and customize our services for an enhanced overall user
            experience.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            You can enable or disable location services when you use our
            services at any time by way of your device settings.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>Tracking Cookies Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We use cookies and similar tracking technologies to track the
            activity on our services and we hold certain information.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyze our services.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our services.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Examples of Cookies we use:
          </Text>
        </Paragraph>

        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.{' '}
            <Text style={styles.descriptionBoldText}>Session Cookies:</Text> We
            use Session Cookies to operate our Service.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.2.{' '}
            <Text style={styles.descriptionBoldText}>Preference Cookies:</Text>{' '}
            We use Preference Cookies to remember your preferences and various
            settings.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.3.{' '}
            <Text style={styles.descriptionBoldText}>Security Cookies:</Text> We
            use Security Cookies for security purposes.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.4.{' '}
            <Text style={styles.descriptionBoldText}>Advertising Cookies:</Text>{' '}
            Advertising Cookies are used to serve you with advertisements that
            may be relevant to you and your interests.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>Other Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            While using our services, we may also collect the following
            information: sex, age, date of birth, nationality, hometown,
            languages you speak, registration at place of residence and actual
            address, mobile number, information on marital status and other
            data.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>5. Use of Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Qongfu Technologies Co SPC uses the collected data for various
            purposes:
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1. to provide and maintain our services;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.2. to notify you about changes to our services;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.3. to allow you to participate in interactive features of our
            services when you choose to do so;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.4. to provide customer support;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.5. to gather analysis or valuable information so that we can
            improve our services;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.6. to monitor the usage of our services;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.7. to detect, prevent and address technical issues;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.8. to fulfil any other purpose for which you provide it;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.9. to carry out our obligations and enforce our rights arising
            from any contracts entered into between you and us, including for
            billing and collection;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.10. to provide you with notices about your account and/or
            subscription, including expiration and renewal notices,
            email-instructions, etc.;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.11. to provide you with news, special offers and general
            information about other goods, services and events which we offer
            that are similar to those that you have already purchased or
            enquired about unless you have opted not to receive such
            information;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.12. in any other way we may describe when you provide the
            information;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.13. for any other purpose with your consent.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>6. Retention of Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period, except when this
            data is used to strengthen the security or to improve the
            functionality of our services, or we are legally obligated to retain
            this data for longer time periods.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>7. Transfer of Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            If you are located outside Bahrain and choose to provide information
            to us, please note that we transfer the data, including Personal
            Data, to Bahrain and process it there.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Qongfu Technologies Co SPC will take all the steps reasonably
            necessary to ensure that your data is treated securely and in
            accordance with this Privacy Policy and no transfer of your Personal
            Data will take place to an organization or a country unless there
            are adequate controls in place including the security of your data
            and other personal information.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>8. Disclosure of Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may disclose personal information that we collect, or you
            provide:
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>
          0.1. Other cases. We may disclose your information also:
        </Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.1. to our subsidiaries and affiliates;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.2. to contractors, service providers, and other third parties we
            use to support our business;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.3. to fulfill the purpose for which you provide it;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.4. for the purpose of including your company’s logo on our
            website;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.5. for any other purpose disclosed by us when you provide the
            information;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.6. with your consent in any other cases;
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            0.1.7. if we believe disclosure is necessary or appropriate to
            protect the rights, property, or safety of the Company, our
            customers, or others.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>9. Security of Data</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>10. Service Providers</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may employ third party companies and individuals to facilitate
            our services{' '}
            <Text style={styles.descriptionBoldText}>
              (“Service Providers”),
            </Text>{' '}
            provide our services on our behalf, perform related services or
            assist us in analyzing how our services are used.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>11. Analytics</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may use third-party Service Providers to monitor and analyze the
            use of our services.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>12. CI/CD tools</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may use third-party Service Providers to automate the development
            process of our services.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>13. Advertising</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may use third-party Service Providers to show advertisements to
            you to help support and maintain our services.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>
          14. Behavioral Remarketing
        </Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may use remarketing services to advertise on third party websites
            to you after you visited our services. We and our third-party
            vendors use cookies to inform, optimize and serve ads based on your
            past visits to our services.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>15. Payments</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may provide paid products and/or services within our services. In
            that case, we use third-party services for payment processing{' '}
            <Text style={styles.descriptionBoldText}>
              (“Payment Processors”) .
            </Text>
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We will not store or collect your payment card details. That
            information is provided directly to our third-party payment
            processors whose use of your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>16. Links to Other Sites</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Our services may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party’s site. We strongly advise you to review the Privacy
            Policy of every site you visit.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            For example, the outlined Privacy Policy has been made using{' '}
            <Text
              style={styles.descriptionLinkText}
              onPress={() => handleOpenLink('policyMaker')}>
              PolicyMaker.io
            </Text>
            , free tool that helps create high-quality legal documents.
            PolicyMaker’s{' '}
            <Text
              style={styles.descriptionLinkText}
              onPress={() => handleOpenLink('privacyPolicy')}>
              free online privacy policy generator
            </Text>{' '}
            is an easy-to-use tool for creating a privacy policy for a website,
            blog, e-commerce store or app.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>17. Children’s Privacy</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            Our services are not intended for use by children under the age of
            16 <Text style={styles.descriptionBoldText}>(“Child”</Text> or{' '}
            <Text style={styles.descriptionBoldText}>“Children”).</Text>
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We do not knowingly collect personally identifiable information from
            Children under 16. If you become aware that a Child has provided us
            with Personal Data, please contact us. If we become aware that we
            have collected Personal Data from Children without verification of
            parental consent, we take steps to remove that information from our
            servers.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>
          18. Changes to This Privacy Policy
        </Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            We will let you know via email and/or a prominent notice on our
            services, prior to the change becoming effective and update
            “effective date” at the top of this Privacy Policy.
          </Text>
        </Paragraph>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </Text>
        </Paragraph>
        <Text style={styles.descriptionHeading}>19. Contact Us</Text>
        <Paragraph style={styles.paragraph}>
          <Text style={styles.descriptionText}>
            If you have any questions about this Privacy Policy, please contact
            us by email:{' '}
            <Text style={styles.descriptionBoldText}>legal@qongfu.com.</Text>
          </Text>
        </Paragraph>
      </View>
    </PageLayout>
  );
};

export default PrivacyPolicy;
